backend:
  name: github
  repo: KenshyDEV/pruebapagina   # ejemplo: kevinvalencia/jbautista
  branch: main              # o master, según tu repo

media_folder: "img/uploads"   # Carpeta en el repo donde se guardan imágenes
public_folder: "/img/uploads" # Cómo se accede públicamente a esas imágenes

collections:
  - name: "blog"
    label: "Blog"
    folder: "post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "image", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }
