backend:
  name: git-gateway
  branch: main  # O la rama principal de tu repo (a veces 'master')

media_folder: "img/uploads"   # Aquí se guardan las imágenes
public_folder: "/img/uploads" # Ruta pública para accederlas

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "image", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }
